### ISSUE TITLE
Handling loss of USB device: folie

### ISSUE THREAD

**Issue by JohnOH** [jeelabs/folib#1]
Please consider an alternative method of handling the loss of the USB device - for instance when the interface is removed. Currently, under Windows, the program exits if the USB cable is removed from the computer. This cause loss of the command history and any displayed output.

Instead might  a dialog box be opened with an option to exit or reconnect, after the interface was replaced.

**Comment by jcw** [comment]
This is an issue regrding the Folie utility, not this Forth library. Please submit to jeelabs/embello.
(I'm no Win expert, but I think console apps cannot open dialog boxes)
